spring:
   mvc:
     pathmatch:
           matching-strategy: ANT_PATH_MATCHER
   datasource:
    url: jdbc:mysql://localhost:3306/stock-app
    username: root
    password: Zensar@123
   jpa:
    properties:
     hibernate:
      format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

      base-path: "/my-actuator"
      
      
  endpoint:
    shutdown:
      enabled: true
      
      

      


        
        

